apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config
  namespace: backend-app

data:
  MY_DATABASE_DRIVER: "mysql"
  DB_HOST: "mysql-service"
  DB_USER_NAME: "root"
  DB_NAME: "appdb"
  DB_PORT: "3306"