apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  namespace: backend-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: kat018/backend-evaluacion

        ports:
        - containerPort: 80

        env:
        - name: MY_DATABASE_DRIVER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: MY_DATABASE_DRIVER

        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_HOST

        - name: DB_USER_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_USER_NAME

        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_NAME

        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_PORT

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASSWORD